<script lang="ts">
  import { onMount } from 'svelte';
  let { recovered, onrecover, onreturn }: { recovered: boolean; onrecover: () => void; onreturn: () => void } = $props();
  let x = $state(480); let y = $state(690); let dx = 0; let dy = 0; let frame = 0;
  const briefing = $derived(Math.hypot(x - 760, y - 360) < 80);
  function move(){if(dx||dy){x=Math.max(100,Math.min(900,x+dx*4));y=Math.max(120,Math.min(760,y+dy*4))}frame=requestAnimationFrame(move)}
  function interact(){if(briefing&&!recovered)onrecover();else if(y>700)onreturn()}
  onMount(()=>{const down=(e:KeyboardEvent)=>{if((e.target as HTMLElement)?.tagName==='INPUT')return;if(['ArrowLeft','a','A'].includes(e.key)){e.preventDefault();dx=-1;dy=0}if(['ArrowRight','d','D'].includes(e.key)){e.preventDefault();dx=1;dy=0}if(['ArrowUp','w','W'].includes(e.key)){e.preventDefault();dx=0;dy=-1}if(['ArrowDown','s','S'].includes(e.key)){e.preventDefault();dx=0;dy=1}if(['e','E','Enter'].includes(e.key))interact()};const up=()=>{dx=0;dy=0};window.addEventListener('keydown',down);window.addEventListener('keyup',up);frame=requestAnimationFrame(move);return()=>{cancelAnimationFrame(frame);window.removeEventListener('keydown',down);window.removeEventListener('keyup',up)}})
</script>
<main class="archive-map illustrated-archive"><header><button onclick={onreturn}>← SENATE</button><div><p>SENATE BASEMENT</p><h1>THE <span>ARCHIVES</span></h1></div><b>Find the Economic Impact Briefing</b></header><section class="archive-room"><div class="archive-shelves shelf-a"></div><div class="archive-shelves shelf-b"></div><div class="archive-shelves shelf-c"></div><div class="archive-desk">RESEARCH<br/>DESK</div><div class:recovered class="briefing-folder" aria-label="Economic Impact Briefing">{recovered?'✓':'BRIEFING'}</div><div class="archive-player" style={`left:${x}px;top:${y}px`}>REP</div>{#if briefing&&!recovered}<div class="archive-prompt">E · TAKE ECONOMIC IMPACT BRIEFING</div>{:else if y>700}<div class="archive-prompt">E · RETURN TO SENATE</div>{/if}</section><div class="corner-map-controls"><button onclick={() => {x=Math.max(100,x-40)}}>◀</button><button onclick={() => {y=Math.max(120,y-40)}}>▲</button><button class="interact" onclick={interact}>E</button><button onclick={() => {y=Math.min(760,y+40)}}>▼</button><button onclick={() => {x=Math.min(900,x+40)}}>▶</button></div></main>
