<script lang="ts">
  let { playerName, route, houseVotes, senateVotes, notebookEntries, influence, score, oncontinue }: {
    playerName: string; route: 'signed' | 'override'; houseVotes: number; senateVotes: number; notebookEntries: number; influence: number; score: number; oncontinue: () => void;
  } = $props();

  let downloaded = $state(false);

  function escapeSvg(value: string) {
    return value.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
  }

  function downloadCertificate() {
    const completion = route === 'override' ? 'VETO OVERRIDE COMPLETED' : 'BILL SIGNED INTO LAW';
    const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="1600" height="1000" viewBox="0 0 1600 1000">
      <rect width="1600" height="1000" fill="#12213a"/>
      <rect x="42" y="42" width="1516" height="916" fill="none" stroke="#d9ad55" stroke-width="10"/>
      <rect x="62" y="62" width="1476" height="876" fill="none" stroke="#b74b45" stroke-width="3"/>
      <text x="800" y="145" fill="#e8b956" font-family="monospace" font-size="30" font-weight="bold" text-anchor="middle" letter-spacing="7">CAPITOL HILL CRAWLER</text>
      <text x="800" y="245" fill="#f4ead8" font-family="sans-serif" font-size="72" font-weight="bold" text-anchor="middle">COMPLETION RECORD</text>
      <circle cx="250" cy="395" r="108" fill="#5f8aa9" stroke="#f4ead8" stroke-width="12"/>
      <text x="250" y="418" fill="#f4ead8" font-family="sans-serif" font-size="64" font-weight="bold" text-anchor="middle">${escapeSvg(playerName.slice(0, 2).toUpperCase())}</text>
      <text x="800" y="370" fill="#f4ead8" font-family="sans-serif" font-size="46" text-anchor="middle">Representative ${escapeSvg(playerName)}</text>
      <text x="800" y="435" fill="#79cf87" font-family="sans-serif" font-size="48" font-weight="bold" text-anchor="middle">${completion}</text>
      <text x="800" y="495" fill="#c7d6e5" font-family="sans-serif" font-size="28" text-anchor="middle">The fictional Connected Classrooms Act became law in this completed campaign.</text>
      <g font-family="sans-serif" text-anchor="middle">
        <rect x="140" y="590" width="290" height="150" fill="#203957" stroke="#66809e" stroke-width="4"/><text x="285" y="640" fill="#a9c0d7" font-size="23">HOUSE SUPPORT</text><text x="285" y="705" fill="#e8b956" font-size="56" font-weight="bold">${houseVotes}</text>
        <rect x="490" y="590" width="290" height="150" fill="#203957" stroke="#66809e" stroke-width="4"/><text x="635" y="640" fill="#a9c0d7" font-size="23">SENATE SUPPORT</text><text x="635" y="705" fill="#e8b956" font-size="56" font-weight="bold">${senateVotes}</text>
        <rect x="840" y="590" width="290" height="150" fill="#203957" stroke="#66809e" stroke-width="4"/><text x="985" y="640" fill="#a9c0d7" font-size="23">NOTEBOOK ENTRIES</text><text x="985" y="705" fill="#e8b956" font-size="56" font-weight="bold">${notebookEntries} / 128</text>
        <rect x="1190" y="590" width="270" height="150" fill="#203957" stroke="#66809e" stroke-width="4"/><text x="1325" y="640" fill="#a9c0d7" font-size="23">FINAL SCORE</text><text x="1325" y="705" fill="#e8b956" font-size="56" font-weight="bold">${score}</text>
      </g>
      <text x="800" y="825" fill="#f4ead8" font-family="sans-serif" font-size="30" text-anchor="middle">Influence remaining: ${influence} INF</text>
      <text x="800" y="885" fill="#a9c0d7" font-family="sans-serif" font-size="22" text-anchor="middle">Generated by Capitol Hill Crawler for classroom completion verification</text>
    </svg>`;
    const image = new Image();
    image.onload = () => {
      const canvas = document.createElement('canvas');
      canvas.width = 1600; canvas.height = 1000;
      const context = canvas.getContext('2d');
      context?.drawImage(image, 0, 0);
      const link = document.createElement('a');
      link.download = `capitol-hill-crawler-${playerName.toLowerCase().replace(/[^a-z]+/g, '-')}-completion.png`;
      link.href = canvas.toDataURL('image/png');
      link.click();
      downloaded = true;
    };
    image.src = `data:image/svg+xml;charset=utf-8,${encodeURIComponent(svg)}`;
  }
</script>

<div class="modal-backdrop"><dialog class="certificate-panel" open aria-labelledby="certificate-title">
  <p class="eyebrow">FINAL SCORE LOCKED</p><h2 id="certificate-title">COMPLETION<br /><span>VERIFIED</span></h2>
  <div class="certificate-preview"><div class="certificate-avatar">{playerName.slice(0, 2).toUpperCase()}</div><div><b>REPRESENTATIVE {playerName.toUpperCase()}</b><p>{route === 'override' ? 'Veto Override Completed' : 'Bill Signed Into Law'}</p></div></div>
  <p>Download this completion record and attach it to your Google Classroom assignment. It includes your name, completion result, vote totals, Notebook progress, remaining INF, and final score.</p>
  <button class="primary" onclick={downloadCertificate}>{downloaded ? 'DOWNLOAD AGAIN' : 'DOWNLOAD COMPLETION RECORD'}</button>
  <p class="certificate-thanks">Special thanks to Mr. AJ DiSantis, Ed-Tech-a-Thon, and Duncan Johnson.</p>
  <button class="text-button" onclick={oncontinue}>RETURN TO TITLE SCREEN</button>
</dialog></div>
