<script lang="ts">
  import { onMount } from 'svelte';
  type Spot={id:string;label:string;x:number;y:number};
  let {minutes,whiteHouseOpen,notebookEntries=0,onrotunda,onspot,onwait}:{minutes:number;whiteHouseOpen:boolean;notebookEntries?:number;onrotunda:()=>void;onspot:(id:string)=>void;onwait:()=>void}=$props();
  let x=$state(2600),y=$state(3300);let hour=$derived(Math.floor(minutes/60)%24),night=$derived(hour>=20||hour<6);
  const spots=$derived<Spot[]>([{id:'capitol',label:'U.S. CAPITOL / ROTUNDA',x:2600,y:3300},{id:'white-house',label:whiteHouseOpen?'WHITE HOUSE':'WHITE HOUSE · LOCKED',x:2600,y:450},{id:'monument',label:'WASHINGTON MONUMENT',x:1700,y:1650},{id:'reflecting',label:'REFLECTING POOL',x:930,y:2450},{id:'lincoln',label:'LINCOLN MEMORIAL',x:380,y:2850},{id:'smithsonian',label:'SMITHSONIAN MUSEUMS',x:2250,y:2450},{id:'library',label:'LIBRARY OF CONGRESS',x:4250,y:2850},{id:'court',label:'SUPREME COURT',x:4400,y:1900},{id:'cafe',label:'MALL CAFE & DINER',x:1850,y:2900},{id:'press',label:'PRESS ROW',x:3350,y:1650},{id:'duncan',label:'DUNCAN JOHNSON',x:820,y:2050},{id:'tourists',label:'TOURISTS & LOCALS',x:3850,y:3400}]);
  let nearby=$derived(spots.find(s=>Math.hypot(s.x-x,s.y-y)<190));
  function nudge(a:number,b:number){x=Math.max(160,Math.min(4840,x+a*105));y=Math.max(180,Math.min(3820,y+b*105))}function interact(){if(nearby)onspot(nearby.id)}
  onMount(()=>{const k=(e:KeyboardEvent)=>{if((e.target as HTMLElement)?.tagName==='INPUT')return;if(e.key==='ArrowLeft'){e.preventDefault();nudge(-1,0)}else if(e.key==='ArrowRight'){e.preventDefault();nudge(1,0)}else if(e.key==='ArrowUp'){e.preventDefault();nudge(0,-1)}else if(e.key==='ArrowDown'){e.preventDefault();nudge(0,1)}else if(['e','E','Enter'].includes(e.key)){e.preventDefault();interact()}};window.addEventListener('keydown',k,true);return()=>window.removeEventListener('keydown',k,true)})
</script>
<main class:night class="dc-overworld-large"><header><button onclick={onrotunda}>← ROTUNDA</button><div><p>WASHINGTON, D.C.</p><h1>NATIONAL <span>MALL</span></h1></div><b>{night?'NIGHT':'DAY'}</b></header><section class="dc-large-view"><div class="dc-large-world" style={`transform:translate(${Math.max(-3700,Math.min(0,650-x))}px,${Math.max(-2950,Math.min(0,450-y))}px)`}><div class="dc-ground"></div><div class="dc-river"></div><div class="dc-path northsouth"></div><div class="dc-path eastwest"></div><div class="curved-walk curved-one"></div><div class="curved-walk curved-two"></div><div class="reflecting-water"></div><div class="smithsonian-complex"><i></i><i></i><i></i><i></i><i></i></div><div class="museum-garden"></div><div class="museum-annex annex-one"></div><div class="museum-annex annex-two"></div><div class="tree-belt north"></div><div class="tree-belt south"></div><div class="tree-belt west"></div><div class="tree-cluster cluster-one"></div><div class="tree-cluster cluster-two"></div><div class="tree-cluster cluster-three"></div><div class="flag-plaza"></div><div class="mall-benches bench-a"></div><div class="mall-benches bench-b"></div><div class="mall-benches bench-c"></div><div class="dc-prop food-cart">HOT<br/>DOGS</div><div class="dc-prop tour-sign">TOUR<br/>MAP</div><div class="dc-prop press-stand">PRESS</div><div class="dc-prop bus-stop">BUS<br/>STOP</div>{#each spots as s}<button class:locked={s.id==='white-house'&&!whiteHouseOpen} class={`dc-site dc-${s.id}`} style={`left:${s.x}px;top:${s.y}px`} onclick={interact}><i></i><b>{s.label}</b></button>{/each}{#each Array(48) as _,i}<div class="dc-large-walker" style={`left:${600+(i*337)%3700}px;top:${1000+(i*191)%2200}px;animation-delay:${(i%6)*-.4}s`}></div>{/each}<div class="dc-large-player" style={`left:${x}px;top:${y}px`}>REP</div></div>{#if nearby}<div class="dc-large-prompt">E · {nearby.label}</div>{/if}</section><div class="corner-map-controls"><button onclick={()=>nudge(0,-1)}>▲</button><button onclick={()=>nudge(-1,0)}>◀</button><button class="interact" onclick={interact}>E</button><button onclick={()=>nudge(1,0)}>▶</button><button onclick={()=>nudge(0,1)}>▼</button></div><button class="wait-button" onclick={onwait}>WAIT UNTIL NEXT {night?'DAY':'NIGHT'}</button></main>
