// Generated by scripts/update-officeholders.mjs from official public sources.
// This file is automatically refreshed on January 28 and August 28.

export const officeholderDataLastVerified = "July 21, 2026";

/** The data must be reviewed by January 28 and August 28 each year. */
export function officeholderDataIsCurrent(today = new Date()) {
  const januaryReview = new Date(today.getFullYear(), 0, 28);
  const augustReview = new Date(today.getFullYear(), 7, 28);
  const mostRecentReview = today >= augustReview ? augustReview : today >= januaryReview ? januaryReview : new Date(today.getFullYear() - 1, 7, 28);
  const lastVerified = new Date(officeholderDataLastVerified);
  return !Number.isNaN(lastVerified.valueOf()) && lastVerified >= mostRecentReview;
}

export const senatorsByState: Record<string, string[]> = {
  "MD": [
    "Angela D. Alsobrooks",
    "Chris Van Hollen"
  ],
  "OK": [
    "Alan Armstrong",
    "James Lankford"
  ],
  "WI": [
    "Tammy Baldwin",
    "Ron Johnson"
  ],
  "IN": [
    "Jim Banks",
    "Todd Young"
  ],
  "WY": [
    "John Barrasso",
    "Cynthia M. Lummis"
  ],
  "CO": [
    "Michael F. Bennet",
    "John W. Hickenlooper"
  ],
  "TN": [
    "Marsha Blackburn",
    "Bill Hagerty"
  ],
  "CT": [
    "Richard Blumenthal",
    "Christopher Murphy"
  ],
  "DE": [
    "Lisa Blunt Rochester",
    "Christopher A. Coons"
  ],
  "NJ": [
    "Cory A. Booker",
    "Andy Kim"
  ],
  "AR": [
    "John Boozman",
    "Tom Cotton"
  ],
  "AL": [
    "Katie Boyd Britt",
    "Tommy Tuberville"
  ],
  "NC": [
    "Ted Budd",
    "Thom Tillis"
  ],
  "WA": [
    "Maria Cantwell",
    "Patty Murray"
  ],
  "WV": [
    "Shelley Moore Capito",
    "James C. Justice"
  ],
  "LA": [
    "Bill Cassidy",
    "John Kennedy"
  ],
  "ME": [
    "Susan M. Collins",
    "Angus S., Jr. King"
  ],
  "TX": [
    "John Cornyn",
    "Ted Cruz"
  ],
  "NV": [
    "Catherine Cortez Masto",
    "Jacky Rosen"
  ],
  "ND": [
    "Kevin Cramer",
    "John Hoeven"
  ],
  "ID": [
    "Mike Crapo",
    "James E. Risch"
  ],
  "UT": [
    "John R. Curtis",
    "Mike Lee"
  ],
  "MT": [
    "Steve Daines",
    "Tim Sheehy"
  ],
  "IL": [
    "Tammy Duckworth",
    "Richard J. Durbin"
  ],
  "IA": [
    "Joni Ernst",
    "Chuck Grassley"
  ],
  "PA": [
    "John Fetterman",
    "David McCormick"
  ],
  "NE": [
    "Deb Fischer",
    "Pete Ricketts"
  ],
  "AZ": [
    "Ruben Gallego",
    "Mark Kelly"
  ],
  "NY": [
    "Kirsten E. Gillibrand",
    "Charles E. Schumer"
  ],
  "SC": [
    "Darline Graham",
    "Tim Scott"
  ],
  "NH": [
    "Margaret Wood Hassan",
    "Jeanne Shaheen"
  ],
  "MO": [
    "Josh Hawley",
    "Eric Schmitt"
  ],
  "NM": [
    "Martin Heinrich",
    "Ben Ray Luján"
  ],
  "HI": [
    "Mazie K. Hirono",
    "Brian Schatz"
  ],
  "OH": [
    "Jon Husted",
    "Bernie Moreno"
  ],
  "MS": [
    "Cindy Hyde-Smith",
    "Roger F. Wicker"
  ],
  "VA": [
    "Tim Kaine",
    "Mark R. Warner"
  ],
  "MN": [
    "Amy Klobuchar",
    "Tina Smith"
  ],
  "MA": [
    "Edward J. Markey",
    "Elizabeth Warren"
  ],
  "KS": [
    "Roger Marshall",
    "Jerry Moran"
  ],
  "KY": [
    "Mitch McConnell",
    "Rand Paul"
  ],
  "OR": [
    "Jeff Merkley",
    "Ron Wyden"
  ],
  "FL": [
    "Ashley Moody",
    "Rick Scott"
  ],
  "AK": [
    "Lisa Murkowski",
    "Dan Sullivan"
  ],
  "GA": [
    "Jon Ossoff",
    "Raphael G. Warnock"
  ],
  "CA": [
    "Alex Padilla",
    "Adam B. Schiff"
  ],
  "MI": [
    "Gary C. Peters",
    "Elissa Slotkin"
  ],
  "RI": [
    "Jack Reed",
    "Sheldon Whitehouse"
  ],
  "SD": [
    "Mike Rounds",
    "John Thune"
  ],
  "VT": [
    "Bernard Sanders",
    "Peter Welch"
  ]
};

export const governorsByStateName: Record<string, string> = {
  "Alabama": "Kay Ivey",
  "Alaska": "Mike Dunleavy",
  "Arizona": "Katie Hobbs",
  "Arkansas": "Sarah Huckabee Sanders",
  "California": "Gavin Newsom",
  "Colorado": "Jared Polis",
  "Connecticut": "Ned Lamont",
  "Delaware": "Matt Meyer",
  "Florida": "Ron DeSantis",
  "Georgia": "Brian Kemp",
  "Hawaii": "Josh Green",
  "Idaho": "Brad Little",
  "Illinois": "JB Pritzker",
  "Indiana": "Mike Braun",
  "Iowa": "Kim Reynolds",
  "Kansas": "Laura Kelly",
  "Kentucky": "Andy Beshear",
  "Louisiana": "Jeff Landry",
  "Maine": "Janet Mills",
  "Maryland": "Wes Moore",
  "Massachusetts": "Maura Healey",
  "Michigan": "Gretchen Whitmer",
  "Minnesota": "Tim Walz",
  "Mississippi": "Tate Reeves",
  "Missouri": "Mike Kehoe",
  "Montana": "Greg Gianforte",
  "Nebraska": "Jim Pillen",
  "Nevada": "Joe Lombardo",
  "New Hampshire": "Kelly Ayotte",
  "New Jersey": "Mikie Sherrill",
  "New Mexico": "Michelle Lujan Grisham",
  "New York": "Kathy Hochul",
  "North Carolina": "Josh Stein",
  "North Dakota": "Kelly Armstrong",
  "Ohio": "Mike DeWine",
  "Oklahoma": "Kevin Stitt",
  "Oregon": "Tina Kotek",
  "Pennsylvania": "Josh Shapiro",
  "Rhode Island": "Dan McKee",
  "South Carolina": "Henry McMaster",
  "South Dakota": "Larry Rhoden",
  "Tennessee": "Bill Lee",
  "Texas": "Greg Abbott",
  "Utah": "Spencer Cox",
  "Vermont": "Phil Scott",
  "Virginia": "Abigail Spanberger",
  "Washington": "Bob Ferguson",
  "West Virginia": "Patrick Morrisey",
  "Wisconsin": "Tony Evers",
  "Wyoming": "Mark Gordon"
};

export const nationalOfficeholders: Record<number, string[]> = {
  30: ['Mike Johnson'],
  38: ['Donald Trump'],
  39: ['JD Vance', 'James David Vance'],
  57: ['John Roberts', 'John G Roberts']
};

export const officeholderSources = {
  senators: "https://www.senate.gov/general/contact_information/senators_cfm.xml",
  governors: "https://www.nga.org/governors/",
  note: 'U.S. Representatives require a separate district-level location or ZIP lookup and are not stored here.'
};
