// Generated by scripts/update-representatives.mjs from official public sources.
// This file is automatically refreshed on the 1st of each month. Do not edit it by hand.
// Logic that depends on this data belongs in a separate module; this file is overwritten wholesale.

export type Representative = { district: number; name: string };

export const representativeDataLastVerified = "September 1, 2026";

/** Keyed by two-letter code. District 0 is an at-large seat, a Delegate, or the Resident Commissioner. */
export const representativesByState: Record<string, Representative[]> = {
  "AL": [
    {
      "district": 1,
      "name": "Barry Moore"
    },
    {
      "district": 2,
      "name": "Shomari Figures"
    },
    {
      "district": 3,
      "name": "Mike Rogers"
    },
    {
      "district": 4,
      "name": "Robert B. Aderholt"
    },
    {
      "district": 5,
      "name": "Dale W. Strong"
    },
    {
      "district": 6,
      "name": "Gary J. Palmer"
    },
    {
      "district": 7,
      "name": "Terri A. Sewell"
    }
  ],
  "FL": [
    {
      "district": 1,
      "name": "Jimmy Patronis"
    },
    {
      "district": 2,
      "name": "Neal P. Dunn"
    },
    {
      "district": 3,
      "name": "Kat Cammack"
    },
    {
      "district": 4,
      "name": "Aaron Bean"
    },
    {
      "district": 5,
      "name": "John H. Rutherford"
    },
    {
      "district": 6,
      "name": "Randy Fine"
    },
    {
      "district": 7,
      "name": "Cory Mills"
    },
    {
      "district": 8,
      "name": "Mike Haridopolos"
    },
    {
      "district": 9,
      "name": "Darren Soto"
    },
    {
      "district": 10,
      "name": "Maxwell Frost"
    },
    {
      "district": 11,
      "name": "Daniel Webster"
    },
    {
      "district": 12,
      "name": "Gus M. Bilirakis"
    },
    {
      "district": 13,
      "name": "Anna Paulina Luna"
    },
    {
      "district": 14,
      "name": "Kathy Castor"
    },
    {
      "district": 15,
      "name": "Laurel M. Lee"
    },
    {
      "district": 16,
      "name": "Vern Buchanan"
    },
    {
      "district": 17,
      "name": "W. Gregory Steube"
    },
    {
      "district": 18,
      "name": "Scott Franklin"
    },
    {
      "district": 19,
      "name": "Byron Donalds"
    },
    {
      "district": 21,
      "name": "Brian J. Mast"
    },
    {
      "district": 22,
      "name": "Lois Frankel"
    },
    {
      "district": 23,
      "name": "Jared Moskowitz"
    },
    {
      "district": 24,
      "name": "Frederica S. Wilson"
    },
    {
      "district": 25,
      "name": "Debbie Wasserman Schultz"
    },
    {
      "district": 26,
      "name": "Mario Diaz-Balart"
    },
    {
      "district": 27,
      "name": "Maria Elvira Salazar"
    },
    {
      "district": 28,
      "name": "Carlos A. Gimenez"
    }
  ],
  "GA": [
    {
      "district": 1,
      "name": "Earl L. \"Buddy\" Carter"
    },
    {
      "district": 2,
      "name": "Sanford D. Bishop, Jr."
    },
    {
      "district": 3,
      "name": "Brian Jack"
    },
    {
      "district": 4,
      "name": "Henry C. \"Hank\" Johnson, Jr."
    },
    {
      "district": 5,
      "name": "Nikema Williams"
    },
    {
      "district": 6,
      "name": "Lucy McBath"
    },
    {
      "district": 7,
      "name": "Richard McCormick"
    },
    {
      "district": 8,
      "name": "Austin Scott"
    },
    {
      "district": 9,
      "name": "Andrew S. Clyde"
    },
    {
      "district": 10,
      "name": "Mike Collins"
    },
    {
      "district": 11,
      "name": "Barry Loudermilk"
    },
    {
      "district": 12,
      "name": "Rick W. Allen"
    },
    {
      "district": 14,
      "name": "Clay Fuller"
    }
  ],
  "CA": [
    {
      "district": 1,
      "name": "James Gallagher"
    },
    {
      "district": 2,
      "name": "Jared Huffman"
    },
    {
      "district": 3,
      "name": "Kevin Kiley"
    },
    {
      "district": 4,
      "name": "Mike Thompson"
    },
    {
      "district": 5,
      "name": "Tom McClintock"
    },
    {
      "district": 6,
      "name": "Ami Bera"
    },
    {
      "district": 7,
      "name": "Doris O. Matsui"
    },
    {
      "district": 8,
      "name": "John Garamendi"
    },
    {
      "district": 9,
      "name": "Josh Harder"
    },
    {
      "district": 10,
      "name": "Mark DeSaulnier"
    },
    {
      "district": 11,
      "name": "Nancy Pelosi"
    },
    {
      "district": 12,
      "name": "Lateefah Simon"
    },
    {
      "district": 13,
      "name": "Adam Gray"
    },
    {
      "district": 15,
      "name": "Kevin Mullin"
    },
    {
      "district": 16,
      "name": "Sam T. Liccardo"
    },
    {
      "district": 17,
      "name": "Ro Khanna"
    },
    {
      "district": 18,
      "name": "Zoe Lofgren"
    },
    {
      "district": 19,
      "name": "Jimmy Panetta"
    },
    {
      "district": 20,
      "name": "Vince Fong"
    },
    {
      "district": 21,
      "name": "Jim Costa"
    },
    {
      "district": 22,
      "name": "David G. Valadao"
    },
    {
      "district": 23,
      "name": "Jay Obernolte"
    },
    {
      "district": 24,
      "name": "Salud O. Carbajal"
    },
    {
      "district": 25,
      "name": "Raul Ruiz"
    },
    {
      "district": 26,
      "name": "Julia Brownley"
    },
    {
      "district": 27,
      "name": "George Whitesides"
    },
    {
      "district": 28,
      "name": "Judy Chu"
    },
    {
      "district": 29,
      "name": "Luz M. Rivas"
    },
    {
      "district": 30,
      "name": "Laura Friedman"
    },
    {
      "district": 31,
      "name": "Gilbert Ray Cisneros, Jr."
    },
    {
      "district": 32,
      "name": "Brad Sherman"
    },
    {
      "district": 33,
      "name": "Pete Aguilar"
    },
    {
      "district": 34,
      "name": "Jimmy Gomez"
    },
    {
      "district": 35,
      "name": "Norma J. Torres"
    },
    {
      "district": 36,
      "name": "Ted Lieu"
    },
    {
      "district": 37,
      "name": "Sydney Kamlager-Dove"
    },
    {
      "district": 38,
      "name": "Linda T. Sánchez"
    },
    {
      "district": 39,
      "name": "Mark Takano"
    },
    {
      "district": 40,
      "name": "Young Kim"
    },
    {
      "district": 41,
      "name": "Ken Calvert"
    },
    {
      "district": 42,
      "name": "Robert Garcia"
    },
    {
      "district": 43,
      "name": "Maxine Waters"
    },
    {
      "district": 44,
      "name": "Nanette Diaz Barragán"
    },
    {
      "district": 45,
      "name": "Derek Tran"
    },
    {
      "district": 46,
      "name": "J. Luis Correa"
    },
    {
      "district": 47,
      "name": "Dave Min"
    },
    {
      "district": 48,
      "name": "Darrell Issa"
    },
    {
      "district": 49,
      "name": "Mike Levin"
    },
    {
      "district": 50,
      "name": "Scott H. Peters"
    },
    {
      "district": 51,
      "name": "Sara Jacobs"
    },
    {
      "district": 52,
      "name": "Juan Vargas"
    }
  ],
  "IN": [
    {
      "district": 1,
      "name": "Frank J. Mrvan"
    },
    {
      "district": 2,
      "name": "Rudy Yakym III"
    },
    {
      "district": 3,
      "name": "Marlin A. Stutzman"
    },
    {
      "district": 4,
      "name": "James R. Baird"
    },
    {
      "district": 5,
      "name": "Victoria Spartz"
    },
    {
      "district": 6,
      "name": "Jefferson Shreve"
    },
    {
      "district": 7,
      "name": "André Carson"
    },
    {
      "district": 8,
      "name": "Mark B. Messmer"
    },
    {
      "district": 9,
      "name": "Erin Houchin"
    }
  ],
  "TX": [
    {
      "district": 1,
      "name": "Nathaniel Moran"
    },
    {
      "district": 2,
      "name": "Dan Crenshaw"
    },
    {
      "district": 3,
      "name": "Keith Self"
    },
    {
      "district": 4,
      "name": "Pat Fallon"
    },
    {
      "district": 5,
      "name": "Lance Gooden"
    },
    {
      "district": 6,
      "name": "Jake Ellzey"
    },
    {
      "district": 7,
      "name": "Lizzie Fletcher"
    },
    {
      "district": 8,
      "name": "Morgan Luttrell"
    },
    {
      "district": 9,
      "name": "Al Green"
    },
    {
      "district": 10,
      "name": "Michael T. McCaul"
    },
    {
      "district": 11,
      "name": "August Pfluger"
    },
    {
      "district": 12,
      "name": "Craig A. Goldman"
    },
    {
      "district": 13,
      "name": "Ronny Jackson"
    },
    {
      "district": 14,
      "name": "Randy K. Weber, Sr."
    },
    {
      "district": 15,
      "name": "Monica De La Cruz"
    },
    {
      "district": 16,
      "name": "Veronica Escobar"
    },
    {
      "district": 17,
      "name": "Pete Sessions"
    },
    {
      "district": 18,
      "name": "Christian D. Menefee"
    },
    {
      "district": 19,
      "name": "Jodey C. Arrington"
    },
    {
      "district": 20,
      "name": "Joaquin Castro"
    },
    {
      "district": 21,
      "name": "Chip Roy"
    },
    {
      "district": 22,
      "name": "Troy E. Nehls"
    },
    {
      "district": 24,
      "name": "Beth Van Duyne"
    },
    {
      "district": 25,
      "name": "Roger Williams"
    },
    {
      "district": 26,
      "name": "Brandon Gill"
    },
    {
      "district": 27,
      "name": "Michael Cloud"
    },
    {
      "district": 28,
      "name": "Henry Cuellar"
    },
    {
      "district": 29,
      "name": "Sylvia R. Garcia"
    },
    {
      "district": 30,
      "name": "Jasmine Crockett"
    },
    {
      "district": 31,
      "name": "John R. Carter"
    },
    {
      "district": 32,
      "name": "Julie Johnson"
    },
    {
      "district": 33,
      "name": "Marc A. Veasey"
    },
    {
      "district": 34,
      "name": "Vicente Gonzalez"
    },
    {
      "district": 35,
      "name": "Greg Casar"
    },
    {
      "district": 36,
      "name": "Brian Babin"
    },
    {
      "district": 37,
      "name": "Lloyd Doggett"
    },
    {
      "district": 38,
      "name": "Wesley Hunt"
    }
  ],
  "NY": [
    {
      "district": 1,
      "name": "Nick LaLota"
    },
    {
      "district": 2,
      "name": "Andrew R. Garbarino"
    },
    {
      "district": 3,
      "name": "Thomas R. Suozzi"
    },
    {
      "district": 4,
      "name": "Laura Gillen"
    },
    {
      "district": 5,
      "name": "Gregory W. Meeks"
    },
    {
      "district": 6,
      "name": "Grace Meng"
    },
    {
      "district": 7,
      "name": "Nydia M. Velázquez"
    },
    {
      "district": 8,
      "name": "Hakeem S. Jeffries"
    },
    {
      "district": 9,
      "name": "Yvette D. Clarke"
    },
    {
      "district": 10,
      "name": "Daniel S. Goldman"
    },
    {
      "district": 11,
      "name": "Nicole Malliotakis"
    },
    {
      "district": 12,
      "name": "Jerrold Nadler"
    },
    {
      "district": 13,
      "name": "Adriano Espaillat"
    },
    {
      "district": 14,
      "name": "Alexandria Ocasio-Cortez"
    },
    {
      "district": 15,
      "name": "Ritchie Torres"
    },
    {
      "district": 16,
      "name": "George Latimer"
    },
    {
      "district": 17,
      "name": "Michael Lawler"
    },
    {
      "district": 18,
      "name": "Patrick Ryan"
    },
    {
      "district": 19,
      "name": "Josh Riley"
    },
    {
      "district": 20,
      "name": "Paul Tonko"
    },
    {
      "district": 21,
      "name": "Elise M. Stefanik"
    },
    {
      "district": 22,
      "name": "John W. Mannion"
    },
    {
      "district": 23,
      "name": "Nicholas A. Langworthy"
    },
    {
      "district": 24,
      "name": "Claudia Tenney"
    },
    {
      "district": 25,
      "name": "Joseph D. Morelle"
    },
    {
      "district": 26,
      "name": "Timothy M. Kennedy"
    }
  ],
  "MO": [
    {
      "district": 1,
      "name": "Wesley Bell"
    },
    {
      "district": 2,
      "name": "Ann Wagner"
    },
    {
      "district": 3,
      "name": "Robert F. Onder, Jr."
    },
    {
      "district": 4,
      "name": "Mark Alford"
    },
    {
      "district": 5,
      "name": "Emanuel Cleaver"
    },
    {
      "district": 6,
      "name": "Sam Graves"
    },
    {
      "district": 7,
      "name": "Eric Burlison"
    },
    {
      "district": 8,
      "name": "Jason Smith"
    }
  ],
  "SC": [
    {
      "district": 1,
      "name": "Nancy Mace"
    },
    {
      "district": 2,
      "name": "Joe Wilson"
    },
    {
      "district": 3,
      "name": "Sheri Biggs"
    },
    {
      "district": 4,
      "name": "William R. Timmons IV"
    },
    {
      "district": 5,
      "name": "Ralph Norman"
    },
    {
      "district": 6,
      "name": "James E. Clyburn"
    },
    {
      "district": 7,
      "name": "Russell Fry"
    }
  ],
  "TN": [
    {
      "district": 1,
      "name": "Diana Harshbarger"
    },
    {
      "district": 2,
      "name": "Tim Burchett"
    },
    {
      "district": 3,
      "name": "Charles J. \"Chuck\" Fleischmann"
    },
    {
      "district": 4,
      "name": "Scott DesJarlais"
    },
    {
      "district": 5,
      "name": "Andrew Ogles"
    },
    {
      "district": 6,
      "name": "John W. Rose"
    },
    {
      "district": 7,
      "name": "Matt Van Epps"
    },
    {
      "district": 8,
      "name": "David Kustoff"
    },
    {
      "district": 9,
      "name": "Steve Cohen"
    }
  ],
  "OK": [
    {
      "district": 1,
      "name": "Kevin Hern"
    },
    {
      "district": 2,
      "name": "Josh Brecheen"
    },
    {
      "district": 3,
      "name": "Frank D. Lucas"
    },
    {
      "district": 4,
      "name": "Tom Cole"
    },
    {
      "district": 5,
      "name": "Stephanie I. Bice"
    }
  ],
  "CT": [
    {
      "district": 1,
      "name": "John B. Larson"
    },
    {
      "district": 2,
      "name": "Joe Courtney"
    },
    {
      "district": 3,
      "name": "Rosa L. DeLauro"
    },
    {
      "district": 4,
      "name": "James A. Himes"
    },
    {
      "district": 5,
      "name": "Jahana Hayes"
    }
  ],
  "AR": [
    {
      "district": 1,
      "name": "Eric A. \"Rick\" Crawford"
    },
    {
      "district": 2,
      "name": "J. French Hill"
    },
    {
      "district": 3,
      "name": "Steve Womack"
    },
    {
      "district": 4,
      "name": "Bruce Westerman"
    }
  ],
  "IL": [
    {
      "district": 1,
      "name": "Jonathan L. Jackson"
    },
    {
      "district": 2,
      "name": "Robin L. Kelly"
    },
    {
      "district": 3,
      "name": "Delia C. Ramirez"
    },
    {
      "district": 4,
      "name": "Jesús G. \"Chuy\" García"
    },
    {
      "district": 5,
      "name": "Mike Quigley"
    },
    {
      "district": 6,
      "name": "Sean Casten"
    },
    {
      "district": 7,
      "name": "Danny K. Davis"
    },
    {
      "district": 8,
      "name": "Raja Krishnamoorthi"
    },
    {
      "district": 9,
      "name": "Janice D. Schakowsky"
    },
    {
      "district": 10,
      "name": "Bradley Scott Schneider"
    },
    {
      "district": 11,
      "name": "Bill Foster"
    },
    {
      "district": 12,
      "name": "Mike Bost"
    },
    {
      "district": 13,
      "name": "Nikki Budzinski"
    },
    {
      "district": 14,
      "name": "Lauren Underwood"
    },
    {
      "district": 15,
      "name": "Mary E. Miller"
    },
    {
      "district": 16,
      "name": "Darin LaHood"
    },
    {
      "district": 17,
      "name": "Eric Sorensen"
    }
  ],
  "CO": [
    {
      "district": 1,
      "name": "Diana DeGette"
    },
    {
      "district": 2,
      "name": "Joe Neguse"
    },
    {
      "district": 3,
      "name": "Jeff Hurd"
    },
    {
      "district": 4,
      "name": "Lauren Boebert"
    },
    {
      "district": 5,
      "name": "Jeff Crank"
    },
    {
      "district": 6,
      "name": "Jason Crow"
    },
    {
      "district": 7,
      "name": "Brittany Pettersen"
    },
    {
      "district": 8,
      "name": "Gabe Evans"
    }
  ],
  "NC": [
    {
      "district": 1,
      "name": "Donald G. Davis"
    },
    {
      "district": 2,
      "name": "Deborah K. Ross"
    },
    {
      "district": 3,
      "name": "Gregory F. Murphy"
    },
    {
      "district": 4,
      "name": "Valerie P. Foushee"
    },
    {
      "district": 5,
      "name": "Virginia Foxx"
    },
    {
      "district": 6,
      "name": "Addison P. McDowell"
    },
    {
      "district": 7,
      "name": "David Rouzer"
    },
    {
      "district": 8,
      "name": "Mark Harris"
    },
    {
      "district": 9,
      "name": "Richard Hudson"
    },
    {
      "district": 10,
      "name": "Pat Harrigan"
    },
    {
      "district": 11,
      "name": "Chuck Edwards"
    },
    {
      "district": 12,
      "name": "Alma S. Adams"
    },
    {
      "district": 13,
      "name": "Brad Knott"
    },
    {
      "district": 14,
      "name": "Tim Moore"
    }
  ],
  "AZ": [
    {
      "district": 1,
      "name": "David Schweikert"
    },
    {
      "district": 2,
      "name": "Elijah Crane"
    },
    {
      "district": 3,
      "name": "Yassamin Ansari"
    },
    {
      "district": 4,
      "name": "Greg Stanton"
    },
    {
      "district": 5,
      "name": "Andy Biggs"
    },
    {
      "district": 6,
      "name": "Juan Ciscomani"
    },
    {
      "district": 7,
      "name": "Adelita S. Grijalva"
    },
    {
      "district": 8,
      "name": "Abraham J. Hamadeh"
    },
    {
      "district": 9,
      "name": "Paul A. Gosar"
    }
  ],
  "VA": [
    {
      "district": 1,
      "name": "Robert J. Wittman"
    },
    {
      "district": 2,
      "name": "Jennifer A. Kiggans"
    },
    {
      "district": 3,
      "name": "Robert C. \"Bobby\" Scott"
    },
    {
      "district": 4,
      "name": "Jennifer L. McClellan"
    },
    {
      "district": 5,
      "name": "John J. McGuire III"
    },
    {
      "district": 6,
      "name": "Ben Cline"
    },
    {
      "district": 7,
      "name": "Eugene Simon Vindman"
    },
    {
      "district": 8,
      "name": "Donald S. Beyer, Jr."
    },
    {
      "district": 9,
      "name": "H. Morgan Griffith"
    },
    {
      "district": 10,
      "name": "Suhas Subramanyam"
    },
    {
      "district": 11,
      "name": "James R. Walkinshaw"
    }
  ],
  "KY": [
    {
      "district": 1,
      "name": "James Comer"
    },
    {
      "district": 2,
      "name": "Brett Guthrie"
    },
    {
      "district": 3,
      "name": "Morgan McGarvey"
    },
    {
      "district": 4,
      "name": "Thomas Massie"
    },
    {
      "district": 5,
      "name": "Harold Rogers"
    },
    {
      "district": 6,
      "name": "Andy Barr"
    }
  ],
  "MD": [
    {
      "district": 1,
      "name": "Andy Harris"
    },
    {
      "district": 2,
      "name": "Johnny Olszewski, Jr."
    },
    {
      "district": 3,
      "name": "Sarah Elfreth"
    },
    {
      "district": 4,
      "name": "Glenn Ivey"
    },
    {
      "district": 5,
      "name": "Steny H. Hoyer"
    },
    {
      "district": 6,
      "name": "April McClain Delaney"
    },
    {
      "district": 7,
      "name": "Kweisi Mfume"
    },
    {
      "district": 8,
      "name": "Jamie Raskin"
    }
  ],
  "MI": [
    {
      "district": 1,
      "name": "Jack Bergman"
    },
    {
      "district": 2,
      "name": "John R. Moolenaar"
    },
    {
      "district": 3,
      "name": "Hillary J. Scholten"
    },
    {
      "district": 4,
      "name": "Bill Huizenga"
    },
    {
      "district": 5,
      "name": "Tim Walberg"
    },
    {
      "district": 6,
      "name": "Debbie Dingell"
    },
    {
      "district": 7,
      "name": "Tom Barrett"
    },
    {
      "district": 8,
      "name": "Kristen McDonald Rivet"
    },
    {
      "district": 9,
      "name": "Lisa C. McClain"
    },
    {
      "district": 10,
      "name": "John James"
    },
    {
      "district": 11,
      "name": "Haley M. Stevens"
    },
    {
      "district": 12,
      "name": "Rashida Tlaib"
    },
    {
      "district": 13,
      "name": "Shri Thanedar"
    }
  ],
  "OH": [
    {
      "district": 1,
      "name": "Greg Landsman"
    },
    {
      "district": 2,
      "name": "David J. Taylor"
    },
    {
      "district": 3,
      "name": "Joyce Beatty"
    },
    {
      "district": 4,
      "name": "Jim Jordan"
    },
    {
      "district": 5,
      "name": "Robert E. Latta"
    },
    {
      "district": 6,
      "name": "Michael A. Rulli"
    },
    {
      "district": 7,
      "name": "Max L. Miller"
    },
    {
      "district": 8,
      "name": "Warren Davidson"
    },
    {
      "district": 9,
      "name": "Marcy Kaptur"
    },
    {
      "district": 10,
      "name": "Michael R. Turner"
    },
    {
      "district": 11,
      "name": "Shontel M. Brown"
    },
    {
      "district": 12,
      "name": "Troy Balderson"
    },
    {
      "district": 13,
      "name": "Emilia Strong Sykes"
    },
    {
      "district": 14,
      "name": "David P. Joyce"
    },
    {
      "district": 15,
      "name": "Mike Carey"
    }
  ],
  "MA": [
    {
      "district": 1,
      "name": "Richard E. Neal"
    },
    {
      "district": 2,
      "name": "James P. McGovern"
    },
    {
      "district": 3,
      "name": "Lori Trahan"
    },
    {
      "district": 4,
      "name": "Jake Auchincloss"
    },
    {
      "district": 5,
      "name": "Katherine M. Clark"
    },
    {
      "district": 6,
      "name": "Seth Moulton"
    },
    {
      "district": 7,
      "name": "Ayanna Pressley"
    },
    {
      "district": 8,
      "name": "Stephen F. Lynch"
    },
    {
      "district": 9,
      "name": "William R. Keating"
    }
  ],
  "PA": [
    {
      "district": 1,
      "name": "Brian K. Fitzpatrick"
    },
    {
      "district": 2,
      "name": "Brendan F. Boyle"
    },
    {
      "district": 3,
      "name": "Dwight Evans"
    },
    {
      "district": 4,
      "name": "Madeleine Dean"
    },
    {
      "district": 5,
      "name": "Mary Gay Scanlon"
    },
    {
      "district": 6,
      "name": "Chrissy Houlahan"
    },
    {
      "district": 7,
      "name": "Ryan Mackenzie"
    },
    {
      "district": 8,
      "name": "Robert P. Bresnahan, Jr."
    },
    {
      "district": 9,
      "name": "Daniel Meuser"
    },
    {
      "district": 10,
      "name": "Scott Perry"
    },
    {
      "district": 11,
      "name": "Lloyd Smucker"
    },
    {
      "district": 12,
      "name": "Summer L. Lee"
    },
    {
      "district": 13,
      "name": "John Joyce"
    },
    {
      "district": 14,
      "name": "Guy Reschenthaler"
    },
    {
      "district": 15,
      "name": "Glenn Thompson"
    },
    {
      "district": 16,
      "name": "Mike Kelly"
    },
    {
      "district": 17,
      "name": "Christopher R. Deluzio"
    }
  ],
  "WA": [
    {
      "district": 1,
      "name": "Suzan K. DelBene"
    },
    {
      "district": 2,
      "name": "Rick Larsen"
    },
    {
      "district": 3,
      "name": "Marie Gluesenkamp Perez"
    },
    {
      "district": 4,
      "name": "Dan Newhouse"
    },
    {
      "district": 5,
      "name": "Michael Baumgartner"
    },
    {
      "district": 6,
      "name": "Emily Randall"
    },
    {
      "district": 7,
      "name": "Pramila Jayapal"
    },
    {
      "district": 8,
      "name": "Kim Schrier"
    },
    {
      "district": 9,
      "name": "Adam Smith"
    },
    {
      "district": 10,
      "name": "Marilyn Strickland"
    }
  ],
  "MN": [
    {
      "district": 1,
      "name": "Brad Finstad"
    },
    {
      "district": 2,
      "name": "Angie Craig"
    },
    {
      "district": 3,
      "name": "Kelly Morrison"
    },
    {
      "district": 4,
      "name": "Betty McCollum"
    },
    {
      "district": 5,
      "name": "Ilhan Omar"
    },
    {
      "district": 6,
      "name": "Tom Emmer"
    },
    {
      "district": 7,
      "name": "Michelle Fischbach"
    },
    {
      "district": 8,
      "name": "Pete Stauber"
    }
  ],
  "WI": [
    {
      "district": 1,
      "name": "Bryan Steil"
    },
    {
      "district": 2,
      "name": "Mark Pocan"
    },
    {
      "district": 3,
      "name": "Derrick Van Orden"
    },
    {
      "district": 4,
      "name": "Gwen Moore"
    },
    {
      "district": 5,
      "name": "Scott Fitzgerald"
    },
    {
      "district": 6,
      "name": "Glenn Grothman"
    },
    {
      "district": 7,
      "name": "Thomas P. Tiffany"
    },
    {
      "district": 8,
      "name": "Tony Wied"
    }
  ],
  "DC": [
    {
      "district": 0,
      "name": "Eleanor Holmes Norton"
    }
  ],
  "NJ": [
    {
      "district": 1,
      "name": "Donald Norcross"
    },
    {
      "district": 2,
      "name": "Jefferson Van Drew"
    },
    {
      "district": 3,
      "name": "Herbert C. Conaway, Jr."
    },
    {
      "district": 4,
      "name": "Christopher H. Smith"
    },
    {
      "district": 5,
      "name": "Josh Gottheimer"
    },
    {
      "district": 6,
      "name": "Frank Pallone, Jr."
    },
    {
      "district": 7,
      "name": "Thomas H. Kean, Jr."
    },
    {
      "district": 8,
      "name": "Robert Menendez"
    },
    {
      "district": 9,
      "name": "Nellie Pou"
    },
    {
      "district": 10,
      "name": "LaMonica McIver"
    },
    {
      "district": 11,
      "name": "Analilia Mejia"
    },
    {
      "district": 12,
      "name": "Bonnie Watson Coleman"
    }
  ],
  "ME": [
    {
      "district": 1,
      "name": "Chellie Pingree"
    },
    {
      "district": 2,
      "name": "Jared F. Golden"
    }
  ],
  "LA": [
    {
      "district": 1,
      "name": "Steve Scalise"
    },
    {
      "district": 2,
      "name": "Troy A. Carter"
    },
    {
      "district": 3,
      "name": "Clay Higgins"
    },
    {
      "district": 4,
      "name": "Mike Johnson"
    },
    {
      "district": 5,
      "name": "Julia Letlow"
    },
    {
      "district": 6,
      "name": "Cleo Fields"
    }
  ],
  "ID": [
    {
      "district": 1,
      "name": "Russ Fulcher"
    },
    {
      "district": 2,
      "name": "Michael K. Simpson"
    }
  ],
  "NE": [
    {
      "district": 1,
      "name": "Mike Flood"
    },
    {
      "district": 2,
      "name": "Don Bacon"
    },
    {
      "district": 3,
      "name": "Adrian Smith"
    }
  ],
  "MS": [
    {
      "district": 1,
      "name": "Trent Kelly"
    },
    {
      "district": 2,
      "name": "Bennie G. Thompson"
    },
    {
      "district": 3,
      "name": "Michael Guest"
    },
    {
      "district": 4,
      "name": "Mike Ezell"
    }
  ],
  "NV": [
    {
      "district": 1,
      "name": "Dina Titus"
    },
    {
      "district": 2,
      "name": "Mark E. Amodei"
    },
    {
      "district": 3,
      "name": "Susie Lee"
    },
    {
      "district": 4,
      "name": "Steven Horsford"
    }
  ],
  "OR": [
    {
      "district": 1,
      "name": "Suzanne Bonamici"
    },
    {
      "district": 2,
      "name": "Cliff Bentz"
    },
    {
      "district": 3,
      "name": "Maxine Dexter"
    },
    {
      "district": 4,
      "name": "Val T. Hoyle"
    },
    {
      "district": 5,
      "name": "Janelle S. Bynum"
    },
    {
      "district": 6,
      "name": "Andrea Salinas"
    }
  ],
  "VI": [
    {
      "district": 0,
      "name": "Stacey E. Plaskett"
    }
  ],
  "AS": [
    {
      "district": 0,
      "name": "Aumua Amata Coleman Radewagen"
    }
  ],
  "KS": [
    {
      "district": 1,
      "name": "Tracey Mann"
    },
    {
      "district": 2,
      "name": "Derek Schmidt"
    },
    {
      "district": 3,
      "name": "Sharice Davids"
    },
    {
      "district": 4,
      "name": "Ron Estes"
    }
  ],
  "HI": [
    {
      "district": 1,
      "name": "Ed Case"
    },
    {
      "district": 2,
      "name": "Jill N. Tokuda"
    }
  ],
  "NH": [
    {
      "district": 1,
      "name": "Chris Pappas"
    },
    {
      "district": 2,
      "name": "Maggie Goodlander"
    }
  ],
  "SD": [
    {
      "district": 0,
      "name": "Dusty Johnson"
    }
  ],
  "WV": [
    {
      "district": 1,
      "name": "Carol D. Miller"
    },
    {
      "district": 2,
      "name": "Riley M. Moore"
    }
  ],
  "IA": [
    {
      "district": 1,
      "name": "Mariannette Miller-Meeks"
    },
    {
      "district": 2,
      "name": "Ashley Hinson"
    },
    {
      "district": 3,
      "name": "Zachary Nunn"
    },
    {
      "district": 4,
      "name": "Randy Feenstra"
    }
  ],
  "NM": [
    {
      "district": 1,
      "name": "Melanie A. Stansbury"
    },
    {
      "district": 2,
      "name": "Gabe Vasquez"
    },
    {
      "district": 3,
      "name": "Teresa Leger Fernandez"
    }
  ],
  "UT": [
    {
      "district": 1,
      "name": "Blake D. Moore"
    },
    {
      "district": 2,
      "name": "Celeste Maloy"
    },
    {
      "district": 3,
      "name": "Mike Kennedy"
    },
    {
      "district": 4,
      "name": "Burgess Owens"
    }
  ],
  "MT": [
    {
      "district": 1,
      "name": "Ryan K. Zinke"
    },
    {
      "district": 2,
      "name": "Troy Downing"
    }
  ],
  "GU": [
    {
      "district": 0,
      "name": "James C. Moylan"
    }
  ],
  "RI": [
    {
      "district": 1,
      "name": "Gabe Amo"
    },
    {
      "district": 2,
      "name": "Seth Magaziner"
    }
  ],
  "VT": [
    {
      "district": 0,
      "name": "Becca Balint"
    }
  ],
  "WY": [
    {
      "district": 0,
      "name": "Harriet M. Hageman"
    }
  ],
  "AK": [
    {
      "district": 0,
      "name": "Nicholas J. Begich III"
    }
  ],
  "DE": [
    {
      "district": 0,
      "name": "Sarah McBride"
    }
  ],
  "MP": [
    {
      "district": 0,
      "name": "Kimberlyn King-Hinds"
    }
  ],
  "ND": [
    {
      "district": 0,
      "name": "Julie Fedorchak"
    }
  ],
  "PR": [
    {
      "district": 0,
      "name": "Pablo José Hernández"
    }
  ]
};

export const representativeSources = {
  roster: "https://unitedstates.github.io/congress-legislators/legislators-current.json",
  districts: "https://raw.githubusercontent.com/OpenSourceActivismTech/us-zipcodes-congress/master/zccd.csv",
  note: 'ZIP codes resolve to districts entirely in the browser. No lookup request ever leaves the device.'
};
